title: Curatur
email: hello@curatur.com
description: >
  Curatur—collaboratively crafted software. With Ruby, Ruby on Rails, JavaScript
  and other technologies, we use Lean and Agile methods to work together with our
  clients to build well-crafted software that stands the test of time.
baseurl: ""
url: http://www.curatur.com
twitter_username: curatur
github_username:  curatur
markdown: kramdown
